<a href="https://colab.research.google.com/github/ShahdMamdouhMuhamed/COVID19-Dashboard-Analysis/blob/main/COVID19_Global_Preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Loading Data**

In [ ]:
url = "https://raw.githubusercontent.com/owid/covid-19-data/refs/heads/master/public/data/owid-covid-data.csv"

In [4]:
import pandas as pd
from google.colab import files


df_raw = pd.read_csv(url, low_memory=False)

df_raw.to_csv('data.csv', index=False)

files.download('data.csv')

print(f"Size: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")

df_raw.head()

Size: 429,435 rows × 67 columns

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

# **Initial Exploration**

In [5]:
print(f"Dataset shape: {df_raw.shape}")

Dataset shape: (429435, 67)

In [6]:
print(f"Columns: {list(df_raw.columns)}")

Columns: ['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed', 'total_deaths', 'new_deaths', 'new_deaths_smoothed', 'total_cases_per_million', 'new_cases_per_million', 'new_cases_smoothed_per_million', 'total_deaths_per_million', 'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients', 'icu_patients_per_million', 'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions', 'weekly_icu_admissions_per_million', 'weekly_hosp_admissions', 'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests', 'total_tests_per_thousand', 'new_tests_per_thousand', 'new_tests_smoothed', 'new_tests_smoothed_per_thousand', 'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated', 'total_boosters', 'new_vaccinations', 'new_vaccinations_smoothed', 'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred', 'new_vaccinations_smoothed_per_million', 'new_people_vaccinated_smoothed', 'new_people_vaccinated_smoothed_per_hundred', 'stringency_index', 'population_density', 'median_age', 'aged_65_older', 'aged_70_older', 'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers', 'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand', 'life_expectancy', 'human_development_index', 'population', 'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative', 'excess_mortality', 'excess_mortality_cumulative_per_million']

In [7]:
print("Data types:", df_raw.dtypes.value_counts())

Data types: float64    61
object      5
int64       1
Name: count, dtype: int64

In [8]:
print("Missing values (top 15 most missing columns):")
print(df_raw.isnull().sum().sort_values(ascending=False).head(15))

Missing values (top 15 most missing columns):
weekly_icu_admissions                      418442
weekly_icu_admissions_per_million          418442
excess_mortality                           416024
excess_mortality_cumulative_absolute       416024
excess_mortality_cumulative                416024
excess_mortality_cumulative_per_million    416024
weekly_hosp_admissions                     404938
weekly_hosp_admissions_per_million         404938
icu_patients_per_million                   390319
icu_patients                               390319
hosp_patients_per_million                  388779
hosp_patients                              388779
total_boosters_per_hundred                 375835
total_boosters                             375835
new_vaccinations                           358464
dtype: int64

In [9]:
print("Date range:", df_raw['date'].min(), "to", df_raw['date'].max())

Date range: 2020-01-01 to 2024-08-14

In [10]:
df_raw.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,NaN,0.0,0.0,NaN,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN

In [11]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  object
 1   continent                                   402910 non-null  object
 2   location                                    429435 non-null  object
 3   date                                        429435 non-null  object
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: float64(61), int64(1), object(5)
memory usage: 219.5+ MB

# **Convert Date & Create Clean Copy**

In [12]:
df_raw['date'] = pd.to_datetime(df_raw['date'])
df_clean = df_raw.copy()
print("Date column converted to datetime")

Date column converted to datetime

In [13]:
df_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 429435 entries, 0 to 429434
Data columns (total 67 columns):
 #   Column                                      Non-Null Count   Dtype
---  ------                                      --------------   -----
 0   iso_code                                    429435 non-null  object
 1   continent                                   402910 non-null  object
 2   location                                    429435 non-null  object
 3   date                                        429435 non-null  datetime64[ns]
 4   total_cases                                 411804 non-null  float64
 5   new_cases                                   410159 non-null  float64
 6   new_cases_smoothed                          408929 non-null  float64
 7   total_deaths                                411804 non-null  float64
 8   new_deaths                                  410608 non-null  float64
 9   new_deaths_smoothed                         409378 non-null  float64
 10  total_cases_per_million                     411804 non-null  float64
 11  new_cases_per_million                       410159 non-null  float64
 12  new_cases_smoothed_per_million              408929 non-null  float64
 13  total_deaths_per_million                    411804 non-null  float64
 14  new_deaths_per_million                      410608 non-null  float64
 15  new_deaths_smoothed_per_million             409378 non-null  float64
 16  reproduction_rate                           184817 non-null  float64
 17  icu_patients                                39116 non-null   float64
 18  icu_patients_per_million                    39116 non-null   float64
 19  hosp_patients                               40656 non-null   float64
 20  hosp_patients_per_million                   40656 non-null   float64
 21  weekly_icu_admissions                       10993 non-null   float64
 22  weekly_icu_admissions_per_million           10993 non-null   float64
 23  weekly_hosp_admissions                      24497 non-null   float64
 24  weekly_hosp_admissions_per_million          24497 non-null   float64
 25  total_tests                                 79387 non-null   float64
 26  new_tests                                   75403 non-null   float64
 27  total_tests_per_thousand                    79387 non-null   float64
 28  new_tests_per_thousand                      75403 non-null   float64
 29  new_tests_smoothed                          103965 non-null  float64
 30  new_tests_smoothed_per_thousand             103965 non-null  float64
 31  positive_rate                               95927 non-null   float64
 32  tests_per_case                              94348 non-null   float64
 33  tests_units                                 106788 non-null  object
 34  total_vaccinations                          85417 non-null   float64
 35  people_vaccinated                           81132 non-null   float64
 36  people_fully_vaccinated                     78061 non-null   float64
 37  total_boosters                              53600 non-null   float64
 38  new_vaccinations                            70971 non-null   float64
 39  new_vaccinations_smoothed                   195029 non-null  float64
 40  total_vaccinations_per_hundred              85417 non-null   float64
 41  people_vaccinated_per_hundred               81132 non-null   float64
 42  people_fully_vaccinated_per_hundred         78061 non-null   float64
 43  total_boosters_per_hundred                  53600 non-null   float64
 44  new_vaccinations_smoothed_per_million       195029 non-null  float64
 45  new_people_vaccinated_smoothed              192177 non-null  float64
 46  new_people_vaccinated_smoothed_per_hundred  192177 non-null  float64
 47  stringency_index                            196190 non-null  float64
 48  population_density                          360492 non-null  float64
 49  median_age                                  334663 non-null  float64
 50  aged_65_older                               323270 non-null  float64
 51  aged_70_older                               331315 non-null  float64
 52  gdp_per_capita                              328292 non-null  float64
 53  extreme_poverty                             211996 non-null  float64
 54  cardiovasc_death_rate                       328865 non-null  float64
 55  diabetes_prevalence                         345911 non-null  float64
 56  female_smokers                              247165 non-null  float64
 57  male_smokers                                243817 non-null  float64
 58  handwashing_facilities                      161741 non-null  float64
 59  hospital_beds_per_thousand                  290689 non-null  float64
 60  life_expectancy                             390299 non-null  float64
 61  human_development_index                     319127 non-null  float64
 62  population                                  429435 non-null  int64
 63  excess_mortality_cumulative_absolute        13411 non-null   float64
 64  excess_mortality_cumulative                 13411 non-null   float64
 65  excess_mortality                            13411 non-null   float64
 66  excess_mortality_cumulative_per_million     13411 non-null   float64
dtypes: datetime64[ns](1), float64(61), int64(1), object(4)
memory usage: 219.5+ MB

# **Remove duplicates**

In [16]:
rows_before = df_raw.shape[0]
print(f"Rows before removing duplicates: {rows_before:,}")

duplicate_count = df_raw.duplicated(subset=['location', 'date']).sum()
df = df_raw.drop_duplicates(subset=['location', 'date'])

rows_after = df.shape[0]
print(f"Rows after removing duplicates: {rows_after:,}")

Rows before removing duplicates: 429,435
Rows after removing duplicates: 421,665

# **Handle Missing Values**

In [18]:
df_clean = df.copy()

print("Missing values BEFORE cleaning:", df_clean.isnull().sum().sum())

# New metrics → fill with 0
new_cols = [col for col in df_clean.columns if col.startswith('new_')]
df_clean[new_cols] = df_clean[new_cols].fillna(0)

# Cumulative totals → forward fill per country
cum_cols = ['total_cases', 'total_deaths', 'total_tests',
            'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
            'icu_patients', 'hosp_patients']
df_clean[cum_cols] = df_clean.groupby('location')[cum_cols].ffill()

# Constant columns (per country) → forward + backward fill
const_cols = ['continent', 'population', 'population_density', 'gdp_per_capita',
              'median_age', 'aged_65_older', 'life_expectancy', 'human_development_index',
              'extreme_poverty', 'diabetes_prevalence']
df_clean[const_cols] = df_clean.groupby('location')[const_cols].ffill().bfill()

# Remaining numeric columns → fill with 0
numeric_cols = df_clean.select_dtypes(include='number').columns
df_clean[numeric_cols] = df_clean[numeric_cols].fillna(0)

print("Missing values AFTER cleaning :", df_clean.isnull().sum().sum())

Missing values BEFORE cleaning: 14202382
Missing values AFTER cleaning : 315184

In [19]:
remaining = df_clean.isnull().sum()
remaining = remaining[remaining > 0].sort_values(ascending=False)
print("Columns that STILL have missing values (these will be dropped later):")
print(remaining)

Columns that STILL have missing values (these will be dropped later):
tests_units    315184
dtype: int64

# **Feature Engineering**

In [25]:
import numpy as np
df_clean['case_fatality_rate'] = (df_clean['total_deaths'] / df_clean['total_cases'] * 100).replace([np.inf, -np.inf], 0).fillna(0)
df_clean['vaccination_rate'] = df_clean['people_fully_vaccinated_per_hundred']
df_clean['year'] = df_clean['date'].dt.year
df_clean['month'] = df_clean['date'].dt.month

print("added derived columns: case_fatality_rate, vaccination_rate, year, month")

added derived columns: case_fatality_rate, vaccination_rate, year, month

# **Select Relevant Columns**

In [26]:
selected_cols = [
    'iso_code', 'continent', 'location', 'date',
    'total_cases', 'new_cases', 'total_deaths', 'new_deaths',
    'total_cases_per_million', 'new_cases_per_million',
    'total_deaths_per_million', 'new_deaths_per_million',
    'total_tests', 'new_tests', 'positive_rate', 'tests_per_case',
    'total_vaccinations', 'people_vaccinated', 'people_fully_vaccinated',
    'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
    'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
    'icu_patients', 'hosp_patients',
    'population', 'population_density', 'gdp_per_capita',
    'median_age', 'aged_65_older', 'life_expectancy', 'human_development_index',
    'extreme_poverty', 'diabetes_prevalence' , 'case_fatality_rate', 'vaccination_rate' , 'year', 'month'
]

df_clean = df_clean[selected_cols]
print(f"Reduced to {df_clean.shape[1]} relevant columns")

Reduced to 38 relevant columns

# **Handle outliers**

In [27]:
print("Outlier detection (IQR method) - No removal performed")

key_cols = ['new_cases', 'new_deaths', 'total_cases_per_million', 'new_cases_per_million']

for col in key_cols:
    Q1 = df_clean[col].quantile(0.25)
    Q3 = df_clean[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = ((df_clean[col] < Q1 - 1.5*IQR) | (df_clean[col] > Q3 + 1.5*IQR)).sum()
    print(f"{col:25} → {outliers:,} potential outliers (kept as real events)")

Outlier detection (IQR method) - No removal performed
new_cases                 → 40,814 potential outliers (kept as real events)
new_deaths                → 26,794 potential outliers (kept as real events)
total_cases_per_million   → 44,177 potential outliers (kept as real events)
new_cases_per_million     → 40,787 potential outliers (kept as real events)

# **Aggregate data**

In [28]:
# ex: monthly summary per continent (for dashboard use)
monthly_agg = df_clean.groupby(['continent', 'year', 'month']).agg({
    'new_cases': 'sum',
    'new_deaths': 'sum',
    'total_vaccinations': 'max'
}).reset_index()

print("monthly aggregation created)")
print(monthly_agg.head())

monthly aggregation created)
  continent  year  month  new_cases  new_deaths  total_vaccinations
0    Africa  2020      1        0.0         0.0                 0.0
1    Africa  2020      2        1.0         0.0                 0.0
2    Africa  2020      3     4565.0       140.0                 0.0
3    Africa  2020      4    26756.0      1625.0                 0.0
4    Africa  2020      5   113256.0      2652.0                 0.0

# **Final Checks**

In [33]:
print("Final Validation:")
print(f"Rows: {df_clean.shape[0]:,}")
print(f"Columns: {df_clean.shape[1]}")
print(f"Missing values: {df_clean.isnull().sum().sum()}")
print(f"Duplicate (location+date): {df_clean.duplicated(subset=['location','date']).sum()}")
print(f"Date range: {df_clean['date'].min().date()} → {df_clean['date'].max().date()}")
print("Data is clean and ready for dashboard")

df_clean.to_csv('clean_data.csv', index=False)
files.download('clean_data.csv')
df_clean.head()

Final Validation:
Rows: 421,665
Columns: 38
Missing values: 0
Duplicate (location+date): 0
Date range: 2020-01-01 → 2024-08-14
Data is clean and ready for dashboard

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,total_cases_per_million,new_cases_per_million,...,median_age,aged_65_older,life_expectancy,human_development_index,extreme_poverty,diabetes_prevalence,case_fatality_rate,vaccination_rate,year,month
0,AFG,Asia,Afghanistan,2020-01-05,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6,2.58,64.83,0.51,1.1,9.59,0.0,0.0,2020,1
1,AFG,Asia,Afghanistan,2020-01-06,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6,2.58,64.83,0.51,1.1,9.59,0.0,0.0,2020,1
2,AFG,Asia,Afghanistan,2020-01-07,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6,2.58,64.83,0.51,1.1,9.59,0.0,0.0,2020,1
3,AFG,Asia,Afghanistan,2020-01-08,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6,2.58,64.83,0.51,1.1,9.59,0.0,0.0,2020,1
4,AFG,Asia,Afghanistan,2020-01-09,0.0,0.0,0.0,0.0,0.0,0.0,...,18.6,2.58,64.83,0.51,1.1,9.59,0.0,0.0,2020,1

In [34]:
df.iloc[1450:1500]

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
1450,AFG,Asia,Afghanistan,2023-12-25,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1451,AFG,Asia,Afghanistan,2023-12-26,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1452,AFG,Asia,Afghanistan,2023-12-27,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1453,AFG,Asia,Afghanistan,2023-12-28,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1454,AFG,Asia,Afghanistan,2023-12-29,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1455,AFG,Asia,Afghanistan,2023-12-30,230075.0,0.0,53.14,7970.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1456,AFG,Asia,Afghanistan,2023-12-31,230375.0,300.0,42.86,7973.0,3.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1457,AFG,Asia,Afghanistan,2024-01-01,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1458,AFG,Asia,Afghanistan,2024-01-02,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1459,AFG,Asia,Afghanistan,2024-01-03,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1460,AFG,Asia,Afghanistan,2024-01-04,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1461,AFG,Asia,Afghanistan,2024-01-05,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1462,AFG,Asia,Afghanistan,2024-01-06,230375.0,0.0,42.86,7973.0,0.0,0.43,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1463,AFG,Asia,Afghanistan,2024-01-07,230642.0,267.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1464,AFG,Asia,Afghanistan,2024-01-08,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1465,AFG,Asia,Afghanistan,2024-01-09,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1466,AFG,Asia,Afghanistan,2024-01-10,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1467,AFG,Asia,Afghanistan,2024-01-11,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1468,AFG,Asia,Afghanistan,2024-01-12,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1469,AFG,Asia,Afghanistan,2024-01-13,230642.0,0.0,38.14,7973.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1470,AFG,Asia,Afghanistan,2024-01-14,230855.0,213.0,30.43,7975.0,2.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1471,AFG,Asia,Afghanistan,2024-01-15,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1472,AFG,Asia,Afghanistan,2024-01-16,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1473,AFG,Asia,Afghanistan,2024-01-17,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1474,AFG,Asia,Afghanistan,2024-01-18,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1475,AFG,Asia,Afghanistan,2024-01-19,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1476,AFG,Asia,Afghanistan,2024-01-20,230855.0,0.0,30.43,7975.0,0.0,0.29,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1477,AFG,Asia,Afghanistan,2024-01-21,231052.0,197.0,28.14,7976.0,1.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1478,AFG,Asia,Afghanistan,2024-01-22,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1479,AFG,Asia,Afghanistan,2024-01-23,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1480,AFG,Asia,Afghanistan,2024-01-24,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1481,AFG,Asia,Afghanistan,2024-01-25,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1482,AFG,Asia,Afghanistan,2024-01-26,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1483,AFG,Asia,Afghanistan,2024-01-27,231052.0,0.0,28.14,7976.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1484,AFG,Asia,Afghanistan,2024-01-28,231310.0,258.0,36.86,7981.0,5.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1485,AFG,Asia,Afghanistan,2024-01-29,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1486,AFG,Asia,Afghanistan,2024-01-30,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1487,AFG,Asia,Afghanistan,2024-01-31,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1488,AFG,Asia,Afghanistan,2024-02-01,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1489,AFG,Asia,Afghanistan,2024-02-02,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1490,AFG,Asia,Afghanistan,2024-02-03,231310.0,0.0,36.86,7981.0,0.0,0.71,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1491,AFG,Asia,Afghanistan,2024-02-04,231521.0,211.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1492,AFG,Asia,Afghanistan,2024-02-05,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1493,AFG,Asia,Afghanistan,2024-02-06,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1494,AFG,Asia,Afghanistan,2024-02-07,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1495,AFG,Asia,Afghanistan,2024-02-08,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1496,AFG,Asia,Afghanistan,2024-02-09,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1497,AFG,Asia,Afghanistan,2024-02-10,231521.0,0.0,30.14,7981.0,0.0,0.00,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1498,AFG,Asia,Afghanistan,2024-02-11,231756.0,235.0,33.57,7982.0,1.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN
1499,AFG,Asia,Afghanistan,2024-02-12,231756.0,0.0,33.57,7982.0,0.0,0.14,...,NaN,37.75,0.5,64.83,0.51,41128772,NaN,NaN,NaN,NaN